import type { Currency } from '@/types'
import { fallbackCurrency } from '@/utils/currencyNames'

// 本地静态币种 — 与后端启动 seed（backend/app/services/currency_seed.py）对齐的 35 种。
const CURRENCIES: Currency[] = [
  { code: 'CNY', name: '人民币', symbol: '¥', decimals: 2 },
  { code: 'USD', name: '美元', symbol: '$', decimals: 2 },
  { code: 'EUR', name: '欧元', symbol: '€', decimals: 2 },
  { code: 'GBP', name: '英镑', symbol: '£', decimals: 2 },
  { code: 'JPY', name: '日元', symbol: '¥', decimals: 0 },
  { code: 'HKD', name: '港币', symbol: 'HK$', decimals: 2 },
  { code: 'KRW', name: '韩元', symbol: '₩', decimals: 0 },
  { code: 'SGD', name: '新加坡元', symbol: 'S$', decimals: 2 },
  { code: 'AUD', name: '澳大利亚元', symbol: 'A$', decimals: 2 },
  { code: 'CAD', name: '加拿大元', symbol: 'C$', decimals: 2 },
  { code: 'TWD', name: '新台币', symbol: 'NT$', decimals: 2 },
  { code: 'THB', name: '泰铢', symbol: '฿', decimals: 2 },
  { code: 'MYR', name: '马来西亚林吉特', symbol: 'RM', decimals: 2 },
  { code: 'VND', name: '越南盾', symbol: '₫', decimals: 0 },
  { code: 'RUB', name: '俄罗斯卢布', symbol: '₽', decimals: 2 },
  { code: 'AED', name: '阿联酋迪拉姆', symbol: 'د.إ', decimals: 2 },
  { code: 'BGN', name: '保加利亚列弗', symbol: 'лв', decimals: 2 },
  { code: 'BRL', name: '巴西雷亚尔', symbol: 'R$', decimals: 2 },
  { code: 'CHF', name: '瑞士法郎', symbol: 'CHF', decimals: 2 },
  { code: 'CZK', name: '捷克克朗', symbol: 'Kč', decimals: 2 },
  { code: 'DKK', name: '丹麦克朗', symbol: 'kr', decimals: 2 },
  { code: 'HUF', name: '匈牙利福林', symbol: 'Ft', decimals: 0 },
  { code: 'IDR', name: '印度尼西亚盾', symbol: 'Rp', decimals: 2 },
  { code: 'ILS', name: '以色列新谢克尔', symbol: '₪', decimals: 2 },
  { code: 'INR', name: '印度卢比', symbol: '₹', decimals: 2 },
  { code: 'ISK', name: '冰岛克朗', symbol: 'kr', decimals: 0 },
  { code: 'MXN', name: '墨西哥比索', symbol: 'Mex$', decimals: 2 },
  { code: 'NOK', name: '挪威克朗', symbol: 'kr', decimals: 2 },
  { code: 'NZD', name: '新西兰元', symbol: 'NZ$', decimals: 2 },
  { code: 'PHP', name: '菲律宾比索', symbol: '₱', decimals: 2 },
  { code: 'PLN', name: '波兰兹罗提', symbol: 'zł', decimals: 2 },
  { code: 'RON', name: '罗马尼亚列伊', symbol: 'lei', decimals: 2 },
  { code: 'SEK', name: '瑞典克朗', symbol: 'kr', decimals: 2 },
  { code: 'TRY', name: '土耳其里拉', symbol: '₺', decimals: 2 },
  { code: 'ZAR', name: '南非兰特', symbol: 'R', decimals: 2 },
  // 其余 ISO 4217 币种兜底；导出前会补上中文名。
  { code: 'AFN', name: 'AFN', symbol: 'AFN', decimals: 2 },
  { code: 'ALL', name: 'ALL', symbol: 'ALL', decimals: 2 },
  { code: 'AMD', name: 'AMD', symbol: 'AMD', decimals: 2 },
  { code: 'ANG', name: 'ANG', symbol: 'ANG', decimals: 2 },
  { code: 'AOA', name: 'AOA', symbol: 'AOA', decimals: 2 },
  { code: 'ARS', name: 'ARS', symbol: 'ARS', decimals: 2 },
  { code: 'AWG', name: 'AWG', symbol: 'AWG', decimals: 2 },
  { code: 'AZN', name: 'AZN', symbol: 'AZN', decimals: 2 },
  { code: 'BAM', name: 'BAM', symbol: 'BAM', decimals: 2 },
  { code: 'BBD', name: 'BBD', symbol: 'BBD', decimals: 2 },
  { code: 'BDT', name: 'BDT', symbol: 'BDT', decimals: 2 },
  { code: 'BHD', name: 'BHD', symbol: 'BHD', decimals: 2 },
  { code: 'BIF', name: 'BIF', symbol: 'BIF', decimals: 2 },
  { code: 'BMD', name: 'BMD', symbol: 'BMD', decimals: 2 },
  { code: 'BND', name: 'BND', symbol: 'BND', decimals: 2 },
  { code: 'BOB', name: 'BOB', symbol: 'BOB', decimals: 2 },
  { code: 'BSD', name: 'BSD', symbol: 'BSD', decimals: 2 },
  { code: 'BTN', name: 'BTN', symbol: 'BTN', decimals: 2 },
  { code: 'BWP', name: 'BWP', symbol: 'BWP', decimals: 2 },
  { code: 'BYN', name: 'BYN', symbol: 'BYN', decimals: 2 },
  { code: 'BZD', name: 'BZD', symbol: 'BZD', decimals: 2 },
  { code: 'CDF', name: 'CDF', symbol: 'CDF', decimals: 2 },
  { code: 'CLP', name: 'CLP', symbol: 'CLP', decimals: 2 },
  { code: 'COP', name: 'COP', symbol: 'COP', decimals: 2 },
  { code: 'CRC', name: 'CRC', symbol: 'CRC', decimals: 2 },
  { code: 'CUP', name: 'CUP', symbol: 'CUP', decimals: 2 },
  { code: 'CVE', name: 'CVE', symbol: 'CVE', decimals: 2 },
  { code: 'DJF', name: 'DJF', symbol: 'DJF', decimals: 2 },
  { code: 'DOP', name: 'DOP', symbol: 'DOP', decimals: 2 },
  { code: 'DZD', name: 'DZD', symbol: 'DZD', decimals: 2 },
  { code: 'EGP', name: 'EGP', symbol: 'EGP', decimals: 2 },
  { code: 'ERN', name: 'ERN', symbol: 'ERN', decimals: 2 },
  { code: 'ETB', name: 'ETB', symbol: 'ETB', decimals: 2 },
  { code: 'FJD', name: 'FJD', symbol: 'FJD', decimals: 2 },
  { code: 'FKP', name: 'FKP', symbol: 'FKP', decimals: 2 },
  { code: 'GEL', name: 'GEL', symbol: 'GEL', decimals: 2 },
  { code: 'GHS', name: 'GHS', symbol: 'GHS', decimals: 2 },
  { code: 'GIP', name: 'GIP', symbol: 'GIP', decimals: 2 },
  { code: 'GMD', name: 'GMD', symbol: 'GMD', decimals: 2 },
  { code: 'GNF', name: 'GNF', symbol: 'GNF', decimals: 2 },
  { code: 'GTQ', name: 'GTQ', symbol: 'GTQ', decimals: 2 },
  { code: 'GYD', name: 'GYD', symbol: 'GYD', decimals: 2 },
  { code: 'HNL', name: 'HNL', symbol: 'HNL', decimals: 2 },
  { code: 'HTG', name: 'HTG', symbol: 'HTG', decimals: 2 },
  { code: 'IQD', name: 'IQD', symbol: 'IQD', decimals: 2 },
  { code: 'IRR', name: 'IRR', symbol: 'IRR', decimals: 2 },
  { code: 'JMD', name: 'JMD', symbol: 'JMD', decimals: 2 },
  { code: 'JOD', name: 'JOD', symbol: 'JOD', decimals: 2 },
  { code: 'KES', name: 'KES', symbol: 'KES', decimals: 2 },
  { code: 'KGS', name: 'KGS', symbol: 'KGS', decimals: 2 },
  { code: 'KHR', name: 'KHR', symbol: 'KHR', decimals: 2 },
  { code: 'KMF', name: 'KMF', symbol: 'KMF', decimals: 2 },
  { code: 'KPW', name: 'KPW', symbol: 'KPW', decimals: 2 },
  { code: 'KWD', name: 'KWD', symbol: 'KWD', decimals: 2 },
  { code: 'KYD', name: 'KYD', symbol: 'KYD', decimals: 2 },
  { code: 'KZT', name: 'KZT', symbol: 'KZT', decimals: 2 },
  { code: 'LAK', name: 'LAK', symbol: 'LAK', decimals: 2 },
  { code: 'LBP', name: 'LBP', symbol: 'LBP', decimals: 2 },
  { code: 'LKR', name: 'LKR', symbol: 'LKR', decimals: 2 },
  { code: 'LRD', name: 'LRD', symbol: 'LRD', decimals: 2 },
  { code: 'LSL', name: 'LSL', symbol: 'LSL', decimals: 2 },
  { code: 'LYD', name: 'LYD', symbol: 'LYD', decimals: 2 },
  { code: 'MAD', name: 'MAD', symbol: 'MAD', decimals: 2 },
  { code: 'MDL', name: 'MDL', symbol: 'MDL', decimals: 2 },
  { code: 'MGA', name: 'MGA', symbol: 'MGA', decimals: 2 },
  { code: 'MKD', name: 'MKD', symbol: 'MKD', decimals: 2 },
  { code: 'MMK', name: 'MMK', symbol: 'MMK', decimals: 2 },
  { code: 'MNT', name: 'MNT', symbol: 'MNT', decimals: 2 },
  { code: 'MOP', name: 'MOP', symbol: 'MOP', decimals: 2 },
  { code: 'MRU', name: 'MRU', symbol: 'MRU', decimals: 2 },
  { code: 'MUR', name: 'MUR', symbol: 'MUR', decimals: 2 },
  { code: 'MVR', name: 'MVR', symbol: 'MVR', decimals: 2 },
  { code: 'MWK', name: 'MWK', symbol: 'MWK', decimals: 2 },
  { code: 'MZN', name: 'MZN', symbol: 'MZN', decimals: 2 },
  { code: 'NAD', name: 'NAD', symbol: 'NAD', decimals: 2 },
  { code: 'NGN', name: 'NGN', symbol: 'NGN', decimals: 2 },
  { code: 'NIO', name: 'NIO', symbol: 'NIO', decimals: 2 },
  { code: 'NPR', name: 'NPR', symbol: 'NPR', decimals: 2 },
  { code: 'OMR', name: 'OMR', symbol: 'OMR', decimals: 2 },
  { code: 'PEN', name: 'PEN', symbol: 'PEN', decimals: 2 },
  { code: 'PGK', name: 'PGK', symbol: 'PGK', decimals: 2 },
  { code: 'PKR', name: 'PKR', symbol: 'PKR', decimals: 2 },
  { code: 'PYG', name: 'PYG', symbol: 'PYG', decimals: 2 },
  { code: 'QAR', name: 'QAR', symbol: 'QAR', decimals: 2 },
  { code: 'RSD', name: 'RSD', symbol: 'RSD', decimals: 2 },
  { code: 'RWF', name: 'RWF', symbol: 'RWF', decimals: 2 },
  { code: 'SAR', name: 'SAR', symbol: 'SAR', decimals: 2 },
  { code: 'SBD', name: 'SBD', symbol: 'SBD', decimals: 2 },
  { code: 'SCR', name: 'SCR', symbol: 'SCR', decimals: 2 },
  { code: 'SDG', name: 'SDG', symbol: 'SDG', decimals: 2 },
  { code: 'SHP', name: 'SHP', symbol: 'SHP', decimals: 2 },
  { code: 'SLE', name: 'SLE', symbol: 'SLE', decimals: 2 },
  { code: 'SOS', name: 'SOS', symbol: 'SOS', decimals: 2 },
  { code: 'SRD', name: 'SRD', symbol: 'SRD', decimals: 2 },
  { code: 'SSP', name: 'SSP', symbol: 'SSP', decimals: 2 },
  { code: 'STN', name: 'STN', symbol: 'STN', decimals: 2 },
  { code: 'SYP', name: 'SYP', symbol: 'SYP', decimals: 2 },
  { code: 'SZL', name: 'SZL', symbol: 'SZL', decimals: 2 },
  { code: 'TJS', name: 'TJS', symbol: 'TJS', decimals: 2 },
  { code: 'TMT', name: 'TMT', symbol: 'TMT', decimals: 2 },
  { code: 'TND', name: 'TND', symbol: 'TND', decimals: 2 },
  { code: 'TOP', name: 'TOP', symbol: 'TOP', decimals: 2 },
  { code: 'TTD', name: 'TTD', symbol: 'TTD', decimals: 2 },
  { code: 'TZS', name: 'TZS', symbol: 'TZS', decimals: 2 },
  { code: 'UAH', name: 'UAH', symbol: 'UAH', decimals: 2 },
  { code: 'UGX', name: 'UGX', symbol: 'UGX', decimals: 2 },
  { code: 'UYU', name: 'UYU', symbol: 'UYU', decimals: 2 },
  { code: 'UZS', name: 'UZS', symbol: 'UZS', decimals: 2 },
  { code: 'VES', name: 'VES', symbol: 'VES', decimals: 2 },
  { code: 'VUV', name: 'VUV', symbol: 'VUV', decimals: 2 },
  { code: 'WST', name: 'WST', symbol: 'WST', decimals: 2 },
  { code: 'XAF', name: 'XAF', symbol: 'XAF', decimals: 2 },
  { code: 'XCD', name: 'XCD', symbol: 'XCD', decimals: 2 },
  { code: 'XOF', name: 'XOF', symbol: 'XOF', decimals: 2 },
  { code: 'XPF', name: 'XPF', symbol: 'XPF', decimals: 2 },
  { code: 'YER', name: 'YER', symbol: 'YER', decimals: 2 },
  { code: 'ZMW', name: 'ZMW', symbol: 'ZMW', decimals: 2 },
  { code: 'ZWG', name: 'ZWG', symbol: 'ZWG', decimals: 2 },
]

const LOCAL_CURRENCIES = CURRENCIES.map((currency) => (
  currency.name === currency.code ? fallbackCurrency(currency.code) : currency
))

export function localGetCurrencies(): Currency[] {
  return LOCAL_CURRENCIES
}

export function localRatesStatus() {
  return { latest: null, source: 'local-static' }
}
