export const CURRENCY_NAMES: Record<string, string> = {
  AFN: '阿富汗尼',
  ALL: '阿尔巴尼亚列克',
  AMD: '亚美尼亚德拉姆',
  ANG: '荷属安的列斯盾',
  AOA: '安哥拉宽扎',
  ARS: '阿根廷比索',
  AWG: '阿鲁巴弗罗林',
  AZN: '阿塞拜疆马纳特',
  BAM: '波黑可兑换马克',
  BBD: '巴巴多斯元',
  BDT: '孟加拉塔卡',
  BHD: '巴林第纳尔',
  BIF: '布隆迪法郎',
  BMD: '百慕大元',
  BND: '文莱元',
  BOB: '玻利维亚诺',
  BSD: '巴哈马元',
  BTN: '不丹努尔特鲁姆',
  BWP: '博茨瓦纳普拉',
  BYN: '白俄罗斯卢布',
  BZD: '伯利兹元',
  CDF: '刚果法郎',
  CLP: '智利比索',
  COP: '哥伦比亚比索',
  CRC: '哥斯达黎加科朗',
  CUP: '古巴比索',
  CVE: '佛得角埃斯库多',
  DJF: '吉布提法郎',
  DOP: '多米尼加比索',
  DZD: '阿尔及利亚第纳尔',
  EGP: '埃及镑',
  ERN: '厄立特里亚纳克法',
  ETB: '埃塞俄比亚比尔',
  FJD: '斐济元',
  FKP: '福克兰群岛镑',
  GEL: '格鲁吉亚拉里',
  GHS: '加纳塞地',
  GIP: '直布罗陀镑',
  GMD: '冈比亚达拉西',
  GNF: '几内亚法郎',
  GTQ: '危地马拉格查尔',
  GYD: '圭亚那元',
  HNL: '洪都拉斯伦皮拉',
  HTG: '海地古德',
  IQD: '伊拉克第纳尔',
  IRR: '伊朗里亚尔',
  JMD: '牙买加元',
  JOD: '约旦第纳尔',
  KES: '肯尼亚先令',
  KGS: '吉尔吉斯斯坦索姆',
  KHR: '柬埔寨瑞尔',
  KMF: '科摩罗法郎',
  KPW: '朝鲜圆',
  KWD: '科威特第纳尔',
  KYD: '开曼群岛元',
  KZT: '哈萨克斯坦坚戈',
  LAK: '老挝基普',
  LBP: '黎巴嫩镑',
  LKR: '斯里兰卡卢比',
  LRD: '利比里亚元',
  LSL: '莱索托洛蒂',
  LYD: '利比亚第纳尔',
  MAD: '摩洛哥迪拉姆',
  MDL: '摩尔多瓦列伊',
  MGA: '马达加斯加阿里亚里',
  MKD: '北马其顿第纳尔',
  MMK: '缅甸元',
  MNT: '蒙古图格里克',
  MOP: '澳门元',
  MRU: '毛里塔尼亚乌吉亚',
  MUR: '毛里求斯卢比',
  MVR: '马尔代夫拉菲亚',
  MWK: '马拉维克瓦查',
  MZN: '莫桑比克梅蒂卡尔',
  NAD: '纳米比亚元',
  NGN: '尼日利亚奈拉',
  NIO: '尼加拉瓜科多巴',
  NPR: '尼泊尔卢比',
  OMR: '阿曼里亚尔',
  PEN: '秘鲁索尔',
  PGK: '巴布亚新几内亚基那',
  PKR: '巴基斯坦卢比',
  PYG: '巴拉圭瓜拉尼',
  QAR: '卡塔尔里亚尔',
  RSD: '塞尔维亚第纳尔',
  RWF: '卢旺达法郎',
  SAR: '沙特里亚尔',
  SBD: '所罗门群岛元',
  SCR: '塞舌尔卢比',
  SDG: '苏丹镑',
  SHP: '圣赫勒拿镑',
  SLE: '塞拉利昂新利昂',
  SOS: '索马里先令',
  SRD: '苏里南元',
  SSP: '南苏丹镑',
  STN: '圣多美和普林西比多布拉',
  SYP: '叙利亚镑',
  SZL: '斯威士兰里兰吉尼',
  TJS: '塔吉克斯坦索莫尼',
  TMT: '土库曼斯坦马纳特',
  TND: '突尼斯第纳尔',
  TOP: '汤加潘加',
  TTD: '特立尼达和多巴哥元',
  TZS: '坦桑尼亚先令',
  UAH: '乌克兰格里夫纳',
  UGX: '乌干达先令',
  UYU: '乌拉圭比索',
  UZS: '乌兹别克斯坦苏姆',
  VES: '委内瑞拉玻利瓦尔',
  VUV: '瓦努阿图瓦图',
  WST: '萨摩亚塔拉',
  XAF: '中非法郎',
  XCD: '东加勒比元',
  XOF: '西非法郎',
  XPF: '太平洋法郎',
  YER: '也门里亚尔',
  ZMW: '赞比亚克瓦查',
  ZWG: '津巴布韦金币',
}

const ZERO_DECIMAL_CURRENCIES = new Set([
  'BIF', 'CLP', 'DJF', 'GNF', 'ISK', 'JPY', 'KMF', 'KRW',
  'PYG', 'VND', 'VUV', 'XAF', 'XOF', 'XPF',
])

const THREE_DECIMAL_CURRENCIES = new Set(['BHD', 'IQD', 'JOD', 'KWD', 'LYD', 'OMR', 'TND'])

export function fallbackCurrency(code: string): CurrencyMeta {
  const decimals = THREE_DECIMAL_CURRENCIES.has(code)
    ? 3
    : ZERO_DECIMAL_CURRENCIES.has(code)
      ? 0
      : 2
  return {
    code,
    name: CURRENCY_NAMES[code] ?? code,
    symbol: code,
    decimals,
  }
}

export interface CurrencyMeta {
  code: string
  name: string
  symbol: string | null
  decimals: number
}
